const enemy1 = new Enemy(
  app.canvasDom.getContext('2d'),
  app.appSize.width,
  app.appSize.height,
  'S',
  200,
  200,
  25,
  [
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'rotate', desiredDirection: 'N' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'move' },
    { name: 'wait' },
    { name: 'rotate', desiredDirection: 'S' },
  ]
)
